#!/usr/bin/php -f 
<?php
    require_once __DIR__ . "/../lib/rogoss/workspace/Setup.php";

    if(file_exists(__DIR__ . "/../loader.php"))
        unlink(__DIR__ . "/../loader.php");

    echo \rogoss\workspace\Setup::create(".")
        ->addLib("lib/rogoss/core")
        ->addLib("lib/rogoss/yafip")
        ->compile("loader.php")

        ? "success"
        : "failed"
    ;

